### ISSUE TITLE
# (Stripe::InvalidRequestError) "No such plan: monthly"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#113]
<table><tr><th>Exception</th><td>(Status 400) (Request req_ts13e0cJEBof4Z) No such plan: monthly</td></tr><tr><th>Last Occurrence</th><td>August 21, 2017 12:11:14 -0400</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:253:in `handle_error_response'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:200:in `rescue in execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:184:in `execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:136:in `execute_request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/request.rb:19:in `request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/create.rb:5:in `create'
[bundle].../gems/stripe-3.0.0/lib/stripe/subscription.rb:24:in `create'
<a href='https://github.com/ajc113/currents/blob/e8a2781b877da825b6fca5bfc7fa04900c86304b/app/models/stripe_subscription.rb#L3'>[app].../app/models/stripe_subscription.rb:3:in `create'</a>
<a href='https://github.com/ajc113/currents/blob/e8a2781b877da825b6fca5bfc7fa04900c86304b/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/ajc113/currents/blob/e8a2781b877da825b6fca5bfc7fa04900c86304b/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
(pry):3:in `block in <main>'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in `find_each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/querying.rb:9:in `find_each'
(pry):1:in `<main>'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
[bundle].../gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
<a href='https://github.com/ajc113/currents/blob/e8a2781b877da825b6fca5bfc7fa04900c86304b/bin/rails#L9'>[app].../bin/rails:9:in `<top (required)>'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/Users/AJ/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/AJ/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'</pre>
Fingerprint: `feb8ed8d79b74053e88ccaaeb0f11785d98a5199`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 21, 2017 12:11:01 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;mildred@aufderhar.name&quot;, created_at: &quot;2017-06-02 14:24:58&quot;, updated_at: &quot;2017-08-21 16:10:59&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;Offshore - Gulf of Maine&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BFo6d1lGs8M8z6&quot;, subscription_id: &quot;sub_B9uQcSZqaSxsA0&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 21, 2017 12:11:03 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 2, email: &quot;aundrea@brakus.name&quot;, created_at: &quot;2017-06-02 14:24:59&quot;, updated_at: &quot;2017-08-21 16:11:02&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;ME&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BFo6754blu5TEv&quot;, subscription_id: &quot;sub_B9uQeLkHFy0vFG&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 21, 2017 12:11:08 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 3, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-02 14:24:59&quot;, updated_at: &quot;2017-08-21 16:11:06&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BFo6vzp94s13Dm&quot;, subscription_id: &quot;sub_B9uQ3lVWPaAAMG&quot;, is_active: true, payment_source: &quot;src_1AohkjLl1LzrhllYdW137rZW&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 21, 2017 12:11:11 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 7, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2017-07-13 02:22:04&quot;, updated_at: &quot;2017-08-21 16:11:10&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;asdfadsf&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BFo6hlnaGlGyJp&quot;, subscription_id: &quot;sub_B9uQguE0DN0EWZ&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 21, 2017 12:11:14 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 64, email: &quot;currentsfishingnetwork@gmail.com&quot;, created_at: &quot;2017-08-20 23:23:19&quot;, updated_at: &quot;2017-08-21 16:11:13&quot;, first_name: &quot;asdlkfj&quot;, last_name: &quot;lkjasdf&quot;, home_port: &quot;jlkjasd&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;j;lajsd&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BFo6UuFqxagI9k&quot;, subscription_id: &quot;sub_BFXrFfGzip9XVX&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
