### ISSUE TITLE
# (NoMethodError) "undefined method `stripe_customer_id' for #<User:0xXXXXXX>"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#121]
<table><tr><th>Exception</th><td>undefined method `stripe_customer_id&#39; for #&lt;User:0x007fc082a5b028&gt;</td></tr><tr><th>Last Occurrence</th><td>August 29, 2017 01:12:41 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activemodel-4.2.7.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/stripe_subscription.rb#L4'>[app].../app/models/stripe_subscription.rb:4:in `create'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/user.rb#L38'>[app].../app/models/user.rb:38:in `create_stripe_customer'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `each'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'
[bundle].../gems/devise-4.3.0/app/controllers/devise/registrations_controller.rb:17:in `create'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:49:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
[bundle].../gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `b4856dc209e8d4e278f1be0f2721af751f38fbe6`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 01:12:41 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 9, email: &quot;currentsfishingnetwork@gmail.com&quot;, created_at: &quot;2017-08-29 01:12:30&quot;, updated_at: &quot;2017-08-29 01:12:30&quot;, first_name: &quot;Brant&quot;, last_name: &quot;Rock&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Get it done&quot;, subscription_tier: nil&gt;</td></tr></table>
