### ISSUE TITLE
# (Stripe::InvalidRequestError) "Unrecognized request URL (GET: /v1/customers/). Please see https://stripe.com/docs or we can help at https://support.stripe.com/."

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#124]
<table><tr><th>Exception</th><td>(Status 404) (Request req_per0yjmHkXtIoC) Unrecognized request URL (GET: /v1/customers/). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.</td></tr><tr><th>Last Occurrence</th><td>August 29, 2017 16:29:45 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:278:in `handle_error_response'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:226:in `rescue in execute_request_with_rescues'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:194:in `execute_request_with_rescues'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:151:in `execute_request'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_operations/request.rb:19:in `request'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_operations/request.rb:58:in `request'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_resource.rb:57:in `refresh'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_resource.rb:64:in `retrieve'
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/stripe_customer.rb#L10'>[app].../app/models/stripe_customer.rb:10:in `retrieve'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/user.rb#L66'>[app].../app/models/user.rb:66:in `has_active_subscription?'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/views/shared/_stripe.html.erb#L1'>[app].../app/views/shared/_stripe.html.erb:1:in `_app_views_shared__stripe_html_erb___1207068640485017811_70007327969660'</a>
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:35:in `render'
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/views/my_account/show.html.erb#L3'>[app].../app/views/my_account/show.html.erb:3:in `_app_views_my_account_show_html_erb__1527539468474014632_70007328301440'</a>
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:100:in `_render_template'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:83:in `render_to_body'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/vendor/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb#L308'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
[bundle].../gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
[bundle].../gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `9648e8307d6100f45f627aad218911ea2d90354a`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 16:29:45 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2017-08-29 16:29:39&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;&quot;, subscription_id: nil, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
