### ISSUE TITLE
# (NoMethodError) "undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#137]
<table><tr><th>Exception</th><td>undefined method `each&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>August 29, 2017 19:57:39 +0000</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/stripe_customer.rb#L23'>[app].../app/models/stripe_customer.rb:23:in `delete_all_sources'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L42'>[app].../app/controllers/stripe_controller.rb:42:in `event_process'</a>
<a href='https://github.com/ajc113/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L19'>[app].../app/controllers/stripe_controller.rb:19:in `block in events'</a></pre>
Fingerprint: `287f3aae96a75bb969440410bed667d489147002`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:23 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpEqrHzNdJet3&quot;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:26 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpEfVd5HR5EZn&quot;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:34 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpEOHaimEH5eT&quot;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:33 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpE3ka4yu4Iz3&quot;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:38 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpEsAE6KF0N9t&quot;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 19:57:39 +0000</td></tr><tr><th>Params</th><td>&quot;cus_BIpEf9qsvm91SK&quot;</td></tr></table>
