### ISSUE TITLE
# (NoMethodError) "undefined method `delete' for nil:NilClass"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#155]
<table><tr><th>Exception</th><td>undefined method `delete&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>October 27, 2017 19:06:41 -0400</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/ajc113/currents/blob/b800e4055ef043cfc49de9946ed25342f13a9565/app/models/stripe_customer.rb#L14'>[app].../app/models/stripe_customer.rb:14:in `delete'</a>
<a href='https://github.com/ajc113/currents/blob/b800e4055ef043cfc49de9946ed25342f13a9565/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/ajc113/currents/blob/b800e4055ef043cfc49de9946ed25342f13a9565/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/ajc113/currents/blob/b800e4055ef043cfc49de9946ed25342f13a9565/app/models/user.rb#L45'>[app].../app/models/user.rb:45:in `delete_stripe_customer'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:292:in `destroy'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:281:in `block in destroy'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:281:in `destroy'
[bundle].../bundler/gems/activeadmin-21c50cafc5bf/lib/active_admin/resource_controller/data_access.rb:178:in `block in destroy_resource'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:77:in `public_send'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:77:in `try!'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:63:in `try'
[bundle].../bundler/gems/activeadmin-21c50cafc5bf/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
[bundle].../bundler/gems/activeadmin-21c50cafc5bf/lib/active_admin/resource_controller/data_access.rb:177:in `destroy_resource'
[bundle].../gems/inherited_resources-1.7.2/lib/inherited_resources/actions.rb:58:in `destroy'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/migration.rb:377:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiler.rb:282:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
[bundle].../gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `1656fb687d5807aeee670978196fda7a96193c19`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>October 27, 2017 19:06:41 -0400</td></tr><tr><th>Params</th><td>#&lt;User id: 7, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2017-07-13 02:22:04&quot;, updated_at: &quot;2017-10-20 20:54:40&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;AJ Costa&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BG6YYb1HPsGsoX&quot;, subscription_id: &quot;sub_BG6YkyZ5VTVpWV&quot;, is_active: true, payment_source: &quot;src_1AuLdeDyDCrOMJ6PghQVJV8Y&quot;, deleted_at: nil&gt;</td></tr></table>
