### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `status' for #<Stripe::StripeObject:0xXXXXXX>"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#156]
<table><tr><th>Exception</th><td>undefined method `status&#39; for #&lt;Stripe::StripeObject:0x007f6f96c0d868&gt;</td></tr><tr><th>Last Occurrence</th><td>December 29, 2017 17:39:19 +0000</td></tr><tr><th>Count</th><td>4</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.2/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/ajc113/currents/blob/ccab882793dc47bff55b011d974d071fd30ba0c6/app/controllers/stripe_controller.rb#L50'>[app].../app/controllers/stripe_controller.rb:50:in `event_process'</a>
<a href='https://github.com/ajc113/currents/blob/ccab882793dc47bff55b011d974d071fd30ba0c6/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `16c67c0a5209ccf86b5b4a9eb340c78fa747d3dc`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>October 29, 2017 17:41:51 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2017-10-20 17:18:20&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>November 04, 2017 14:37:57 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 5, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2017-07-12 19:38:41&quot;, updated_at: &quot;2017-10-23 15:09:01&quot;, first_name: &quot;Allen&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Plymouth&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Obsession&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpEsAE6KF0N9t&quot;, subscription_id: &quot;sub_BL1lK2CMGFTRgv&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>November 29, 2017 17:40:20 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2017-11-21 19:09:18&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>December 29, 2017 17:39:19 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2017-12-27 22:19:16&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>January 29, 2018 17:39:13 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-01-02 00:04:27&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>February 28, 2018 18:24:06 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-02-26 20:39:57&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>March 29, 2018 17:39:22 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-03-29 03:12:40&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>April 29, 2018 17:42:11 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-04-23 18:49:03&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CMJX5DyDCrOMJ6Pm7AROEY9</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 29, 2018 17:38:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-05-25 02:01:08&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CXBmNDyDCrOMJ6Pg8uShn5r</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>June 29, 2018 17:40:31 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-06-19 16:23:34&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CiQa7DyDCrOMJ6P3LkSCaP8</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>July 29, 2018 17:40:07 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-07-23 19:30:32&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CtIs8DyDCrOMJ6PS9dafexo</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2018 17:48:51 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-08-25 23:35:52&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1D4XmfDyDCrOMJ6PdY5wulPf</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>September 29, 2018 17:43:50 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-09-18 01:30:08&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1DFmTpDyDCrOMJ6P0m32a1Tt</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>October 29, 2018 17:39:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-10-02 16:09:36&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1DQehyDyDCrOMJ6PrtTDGY0v</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>November 29, 2018 17:45:48 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-11-13 16:49:01&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1Dbta9DyDCrOMJ6PjoZLcL1d</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>December 29, 2018 17:41:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-12-09 23:12:09&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1DmloXDyDCrOMJ6P9slJ0xLG</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>January 29, 2019 17:39:39 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-01-04 20:34:16&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1Dy0YgDyDCrOMJ6PZcl68LrJ</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>February 28, 2019 17:38:18 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-01-04 20:34:16&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1E8sppDyDCrOMJ6PPgcd28E7</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>March 29, 2019 17:38:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-03-20 19:12:46&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1EJOeeDyDCrOMJ6PF8YdI8XQ</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>April 29, 2019 17:38:07 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-04-28 20:56:39&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1EUdQYDyDCrOMJ6PlDBOOKfd</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 29, 2019 17:38:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-05-22 12:57:48&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1EfVj6DyDCrOMJ6P8U2uV30j</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>June 29, 2019 17:38:09 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-06-14 16:40:15&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1EqkV2DyDCrOMJ6PG5446In0</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>July 29, 2019 17:38:15 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-07-19 23:40:02&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1F1cnaDyDCrOMJ6PUl6yBqpl</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2019 17:38:18 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-08-09 16:29:51&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1FCrZdDyDCrOMJ6PN6mmGGym</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>September 29, 2019 17:38:16 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-09-19 23:18:38&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1FO6LbDyDCrOMJ6P3xI1MDo2</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>October 29, 2019 17:38:15 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-10-22 21:42:50&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1FYye2DyDCrOMJ6PdlQmA7Eh</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>November 29, 2019 17:38:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-10-22 21:42:50&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1FkDQ0DyDCrOMJ6PZcoAAwym</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>December 29, 2019 17:38:15 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2019-12-21 00:02:43&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1Fv5iUDyDCrOMJ6PJ61WBivb</td></tr></table></td></tr></table>
