### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `trial_end' for #<Stripe::StripeObject:0xXXXXXX>"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#160]
<table><tr><th>Exception</th><td>undefined method `trial_end&#39; for #&lt;Stripe::StripeObject:0x007fbf24e01290&gt;</td></tr><tr><th>Last Occurrence</th><td>November 04, 2017 15:38:11 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.2/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/ajc113/currents/blob/ccab882793dc47bff55b011d974d071fd30ba0c6/app/controllers/stripe_controller.rb#L58'>[app].../app/controllers/stripe_controller.rb:58:in `event_process'</a>
<a href='https://github.com/ajc113/currents/blob/ccab882793dc47bff55b011d974d071fd30ba0c6/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `b9638edd83eb81f9c3103f86586fcac4f64236ea`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>November 04, 2017 15:38:11 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 5, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2017-07-12 19:38:41&quot;, updated_at: &quot;2017-10-23 15:09:01&quot;, first_name: &quot;Allen&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Plymouth&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Obsession&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpEsAE6KF0N9t&quot;, subscription_id: &quot;sub_BL1lK2CMGFTRgv&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>April 16, 2018 01:11:46 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 23, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2018-03-16 19:55:57&quot;, updated_at: &quot;2018-04-16 00:11:03&quot;, first_name: &quot;Jake&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Plymouth&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Get Bent&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CVPTJEQ9l5LCR4&quot;, subscription_id: &quot;sub_CVPTe3SCnH6LJ4&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CHLsdDyDCrOMJ6PpNU9eeqL</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 09, 2018 01:03:02 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 24, email: &quot;garrettwilga@gmail.com&quot;, created_at: &quot;2018-04-08 23:22:54&quot;, updated_at: &quot;2018-05-09 00:02:26&quot;, first_name: &quot;Garrett&quot;, last_name: &quot;Wilga&quot;, home_port: &quot;Chatham harbor &quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Little rascal &quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_Ce50bhb5mGPIZP&quot;, subscription_id: &quot;sub_Ce50dsIHcimTKd&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CPghrDyDCrOMJ6PfSuO1CnC</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 09, 2018 01:03:07 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;garrettwilg@gmail.com&quot;, created_at: &quot;2018-04-08 23:24:40&quot;, updated_at: &quot;2018-05-09 00:02:40&quot;, first_name: &quot;Garrett&quot;, last_name: &quot;WIlga&quot;, home_port: &quot;Chatham harbor &quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Little rascal &quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_Ce52eWnIykC5UQ&quot;, subscription_id: &quot;sub_Ce523VUmBt5DjK&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CPghsDyDCrOMJ6PxP9uHwEm</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 16, 2018 01:14:17 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 26, email: &quot;ronconimt@gmail.com&quot;, created_at: &quot;2018-04-15 17:13:50&quot;, updated_at: &quot;2018-05-16 00:13:08&quot;, first_name: &quot;Michael&quot;, last_name: &quot;Ronconi&quot;, home_port: &quot;Orleans&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Andiamo&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_Cgbd38FtXbSVYo&quot;, subscription_id: &quot;sub_Cgbdzscw8BnlaC&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CSEDaDyDCrOMJ6PSAvCZyk9</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 18, 2018 01:02:21 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 27, email: &quot;jordanschemenaur@yahoo.com&quot;, created_at: &quot;2018-04-17 03:12:26&quot;, updated_at: &quot;2018-05-18 00:01:27&quot;, first_name: &quot;Jordan&quot;, last_name: &quot;Schemenaur&quot;, home_port: &quot;Sandwich&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Cory Dean&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_Ch8WBh3G8hrfai&quot;, subscription_id: &quot;sub_Ch8WO0x4Lm4oWn&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CSwyvDyDCrOMJ6PNlZNtizg</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>May 30, 2018 01:11:33 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 29, email: &quot;jeremiahmulcahy@yahoo.com&quot;, created_at: &quot;2018-04-29 03:31:34&quot;, updated_at: &quot;2018-05-30 00:11:21&quot;, first_name: &quot;Jerry&quot;, last_name: &quot;Mulcahy&quot;, home_port: &quot;Green Harbor, MA&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Relentless&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CldXqjFnNUJJZe&quot;, subscription_id: &quot;sub_CldXgnMGjzL8kg&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CXIqaDyDCrOMJ6PE7mDjKjC</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>June 29, 2018 18:40:43 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-06-19 16:23:34&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CiRWMDyDCrOMJ6Pz5uVDNx1</td></tr></table></td></tr></table>
