### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `last4' for #<Stripe::Source:0xXXXXXX>"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#201]
<table><tr><th>Exception</th><td>undefined method `last4&#39; for #&lt;Stripe::Source:0x007fbcb4155540&gt;</td></tr><tr><th>Last Occurrence</th><td>June 29, 2018 18:40:43 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.2/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/ajc113/currents/blob/771fa211fa1bc8056ac9e999d92287c059122399/app/controllers/stripe_controller.rb#L91'>[app].../app/controllers/stripe_controller.rb:91:in `event_process'</a>
<a href='https://github.com/ajc113/currents/blob/771fa211fa1bc8056ac9e999d92287c059122399/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `5916cec9cf611e86cf0ed679b92fb9d67b787aa5`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>June 29, 2018 18:40:43 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-06-19 16:23:34&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>charge.failed</td></tr><tr><th>event_id</th><td>evt_1CiRWMDyDCrOMJ6P4Y4rUPta</td></tr></table></td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>July 02, 2018 18:41:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 1, email: &quot;costa.aj@gmail.com&quot;, created_at: &quot;2017-06-09 04:35:10&quot;, updated_at: &quot;2018-06-19 16:23:34&quot;, first_name: &quot;AJ&quot;, last_name: &quot;Costa&quot;, home_port: &quot;Green Harbor&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;Tradition&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BIpE6WzhU6DycB&quot;, subscription_id: &quot;sub_BIpEEKsrJOKa66&quot;, is_active: true, payment_source: &quot;src_1AwDclDyDCrOMJ6PQEroTKCg&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>charge.failed</td></tr><tr><th>event_id</th><td>evt_1CjWxWDyDCrOMJ6PM9yGBnwp</td></tr></table></td></tr></table>
