### ISSUE TITLE
# (Gibbon::MailChimpError) "the server responded with status 400 @title="Invalid Resource", @detail="zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we're not allowing more signups for now", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Invalid Resource", "status"=>400, "detail"=>"zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we're not allowing more signups for now", "instance"=>"09ae5d06-3cac-4fe5-9270-7879041549e9"}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Invalid Resource\",\"status\":400,\"detail\":\"zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we're not allowing more signups for now\",\"instance\":\"09ae5d06-3cac-4fe5-9270-7879041549e9\"}", @status_code=400"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#216]
<table><tr><th>Exception</th><td>the server responded with status 400 @title=&quot;Invalid Resource&quot;, @detail=&quot;zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we&#39;re not allowing more signups for now&quot;, @body={&quot;type&quot;=&gt;&quot;http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/&quot;, &quot;title&quot;=&gt;&quot;Invalid Resource&quot;, &quot;status&quot;=&gt;400, &quot;detail&quot;=&gt;&quot;zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we&#39;re not allowing more signups for now&quot;, &quot;instance&quot;=&gt;&quot;09ae5d06-3cac-4fe5-9270-7879041549e9&quot;}, @raw_body=&quot;{\&quot;type\&quot;:\&quot;http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\&quot;,\&quot;title\&quot;:\&quot;Invalid Resource\&quot;,\&quot;status\&quot;:400,\&quot;detail\&quot;:\&quot;zhofyarnfk8a@mail.ru has signed up to a lot of lists very recently; we&#39;re not allowing more signups for now\&quot;,\&quot;instance\&quot;:\&quot;09ae5d06-3cac-4fe5-9270-7879041549e9\&quot;}&quot;, @status_code=400</td></tr><tr><th>Last Occurrence</th><td>March 12, 2019 02:31:51 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/gibbon-3.2.0/lib/gibbon/api_request.rb:134:in `handle_error'
[bundle].../gems/gibbon-3.2.0/lib/gibbon/api_request.rb:18:in `rescue in post'
[bundle].../gems/gibbon-3.2.0/lib/gibbon/api_request.rb:12:in `post'
[bundle].../gems/gibbon-3.2.0/lib/gibbon/request.rb:47:in `create'
<a href='https://github.com/ajc113/currents/blob/dba2512ab916896b911945d5e54b5df2c2c4f17a/app/models/user.rb#L58'>[app].../app/models/user.rb:58:in `add_user_to_list'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `each'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:506:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'
[bundle].../gems/devise-4.5.0/app/controllers/devise/registrations_controller.rb:19:in `create'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
[bundle].../gems/sentry-raven-2.8.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:312:in `block in halting'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:49:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/rack-cache-1.8.0/lib/rack/cache/context.rb:140:in `forward'
[bundle].../gems/rack-cache-1.8.0/lib/rack/cache/context.rb:147:in `pass'
[bundle].../gems/rack-cache-1.8.0/lib/rack/cache/context.rb:159:in `invalidate'
[bundle].../gems/rack-cache-1.8.0/lib/rack/cache/context.rb:74:in `call!'
[bundle].../gems/rack-cache-1.8.0/lib/rack/cache/context.rb:51:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
[bundle].../gems/sentry-raven-2.8.0/lib/raven/integrations/rack.rb:51:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
[bundle].../gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
[bundle].../gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
[bundle].../gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
[bundle].../gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'</pre>
Fingerprint: `7e6e2fac190bacd6539333730bf34722a08431d2`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>March 12, 2019 02:31:51 +0000</td></tr><tr><th>Params</th><td>&quot;#&lt;User id: 263, email: \&quot;zhofyarnfk8a@mail.ru\&quot;, created_at: \&quot;2019-03-12 02:31:48\&quot;, updated_at: \&quot;2019-03-12 02:31:48\&quot;, first_name: \&quot;Raymonduners\&quot;, last_name: \&quot;Raymonduners\&quot;, home_port: \&quot;Laurel, MD\&quot;, state_waters: \&quot;RI\&quot;, vessel_name: \&quot;Raymonduners\&quot;, subscription_tier: nil, stripe_customer_id: \&quot;cus_EgN9SkauSHxZx3\&quot;, subscription_id: nil, is_active: true, payment_source: nil, deleted_at: nil&gt;&quot;</td></tr></table>
