### ISSUE TITLE
Admin::LocationsController#edit (ActionView::Template::Error) "undefined method `state_waters' for #<Location:0xXXXXXX>"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#56]
<table><tr><th>Exception</th><td>undefined method `state_waters&#39; for #&lt;Location:0x007f79f003e258&gt;</td></tr><tr><th>Last Occurrence</th><td>March 14, 2017 02:27:51 +0000</td></tr><tr><th>Count</th><td>3</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activemodel-4.2.5.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
[bundle].../gems/ransack-1.8.2/lib/ransack/helpers/form_builder.rb:10:in `value'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/tags/base.rb:38:in `value_before_type_cast'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/tags/text_field.rb:13:in `block in render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/tags/text_field.rb:13:in `fetch'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/tags/text_field.rb:13:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/form_helper.rb:787:in `text_field'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/form_helper.rb:1323:in `text_field'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/base/stringish.rb:10:in `block in to_html'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/base/wrapping.rb:11:in `input_wrapping'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/form_builder.rb:6:in `input_wrapping'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/base/stringish.rb:8:in `to_html'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/helpers/input_helper.rb:242:in `input'
[bundle].../gems/arbre-1.1.1/lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:65:in `input'
<a href='https://github.com/ajc113/currents/blob/50856a3180ff8f81d6496626bb509c24b0c09fbd/app/admin/location.rb#L12'>[app].../app/admin/location.rb:12:in `block (3 levels) in <top (required)>'</a>
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:53:in `call'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:53:in `block (2 levels) in inputs'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:52:in `block in inputs'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:58:in `inputs'
<a href='https://github.com/ajc113/currents/blob/50856a3180ff8f81d6496626bb509c24b0c09fbd/app/admin/location.rb#L9'>[app].../app/admin/location.rb:9:in `block (2 levels) in <top (required)>'</a>
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/components/active_admin_form.rb:35:in `build'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/form.rb:25:in `main_content'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:93:in `block (2 levels) in build_main_content_wrapper'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:92:in `block in build_main_content_wrapper'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:91:in `build_main_content_wrapper'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:77:in `block in build_page_content'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:76:in `build_page_content'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:50:in `block in build_page'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:49:in `build_page'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/lib/active_admin/views/pages/base.rb:10:in `build'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/app/views/active_admin/resource/edit.html.arb:2:in `block in _vendor_bundle_ruby_______bundler_gems_activeadmin____b__f__cd__app_views_active_admin_resource_edit_html_arb___1178588867939287612_70080847199300'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:45:in `instance_eval'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:45:in `initialize'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/app/views/active_admin/resource/edit.html.arb:1:in `new'
[bundle].../bundler/gems/activeadmin-795b73f30cd9/app/views/active_admin/resource/edit.html.arb:1:in `_vendor_bundle_ruby_______bundler_gems_activeadmin____b__f__cd__app_views_active_admin_resource_edit_html_arb___1178588867939287612_70080847199300'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:100:in `_render_template'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:83:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
<a href='https://github.com/ajc113/currents/blob/50856a3180ff8f81d6496626bb509c24b0c09fbd/vendor/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb#L303'>[app].../vendor/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'</a>
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:238:in `default_render'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:170:in `to_html'
[bundle].../gems/responders-2.3.0/lib/responders/flash_responder.rb:107:in `to_html'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:163:in `respond'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:156:in `call'
[bundle].../gems/responders-2.3.0/lib/action_controller/respond_with.rb:205:in `respond_with'
[bundle].../gems/inherited_resources-1.7.0/lib/inherited_resources/actions.rb:25:in `edit'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:815:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
[bundle].../gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
[bundle].../gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
[bundle].../gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
[bundle].../gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `call'
[bundle].../gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `4ac00011a0cc802c97c980d1c208bfb14ac7d81f`

**Comment by ajc113** [comment]
fixed rb relationship issue
