### ISSUE TITLE
Admin::LocationsController#index (ActionView::Template::Error) "PG::UndefinedTable: ERROR:  relation "species" does not exist
LINE 1: SELECT "species".* FROM "species"
                                ^
: SELECT "species".* FROM "species""

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#57]
<table><tr><th>Exception</th><td>PG::UndefinedTable: ERROR:  relation &quot;species&quot; does not exist
LINE 1: SELECT &quot;species&quot;.* FROM &quot;species&quot;
                                ^
: SELECT &quot;species&quot;.* FROM &quot;species&quot;</td></tr><tr><th>Last Occurrence</th><td>March 14, 2017 02:12:56 +0000</td></tr><tr><th>Count</th><td>9</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:355:in `select'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/querying.rb:39:in `find_by_sql'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/relation.rb:639:in `exec_queries'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/relation.rb:515:in `load'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/relation.rb:243:in `to_a'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `map'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/base/collections.rb:58:in `collection'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/inputs/filters/select_input.rb:43:in `collection'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/select_input.rb:173:in `select_html'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/select_input.rb:168:in `block in to_html'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/inputs/filters/base.rb:12:in `input_wrapping'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/inputs/select_input.rb:166:in `to_html'
[bundle].../gems/formtastic-3.1.5/lib/formtastic/helpers/input_helper.rb:242:in `input'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/forms.rb:14:in `filter'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/forms.rb:62:in `block (2 levels) in active_admin_filters_form_for'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/forms.rb:58:in `each'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/forms.rb:58:in `block in active_admin_filters_form_for'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/helpers/form_helper.rb:444:in `form_for'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/forms.rb:57:in `active_admin_filters_form_for'
[bundle].../gems/arbre-1.1.1/lib/arbre/element.rb:180:in `method_missing'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/filters/resource_extension.rb:146:in `block in filters_sidebar_section'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/components/sidebar_section.rb:25:in `instance_exec'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/components/sidebar_section.rb:25:in `build_sidebar_content'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/components/sidebar_section.rb:13:in `build'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `sidebar_section'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:132:in `block (2 levels) in build_sidebar'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:131:in `collect'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:131:in `block in build_sidebar'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:130:in `build_sidebar'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:78:in `block in build_page_content'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:76:in `build_page_content'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:50:in `block in build_page'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:49:in `build_page'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/views/pages/base.rb:10:in `build'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
[bundle].../gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/app/views/active_admin/resource/index.html.arb:2:in `block in _vendor_bundle_ruby_______bundler_gems_activeadmin_____ac__dc_d_app_views_active_admin_resource_index_html_arb__4441295432425387593_69928538627420'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:45:in `instance_eval'
[bundle].../gems/arbre-1.1.1/lib/arbre/context.rb:45:in `initialize'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/app/views/active_admin/resource/index.html.arb:1:in `new'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/app/views/active_admin/resource/index.html.arb:1:in `_vendor_bundle_ruby_______bundler_gems_activeadmin_____ac__dc_d_app_views_active_admin_resource_index_html_arb__4441295432425387593_69928538627420'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:100:in `_render_template'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:83:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
<a href='https://github.com/ajc113/currents/blob/50856a3180ff8f81d6496626bb509c24b0c09fbd/vendor/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb#L303'>[app].../vendor/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'</a>
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:238:in `default_render'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:170:in `to_html'
[bundle].../gems/responders-2.3.0/lib/responders/flash_responder.rb:107:in `to_html'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:163:in `respond'
[bundle].../gems/responders-2.3.0/lib/action_controller/responder.rb:156:in `call'
[bundle].../gems/responders-2.3.0/lib/action_controller/respond_with.rb:205:in `respond_with'
[bundle].../gems/inherited_resources-1.7.0/lib/inherited_resources/actions.rb:7:in `index'
[bundle].../bundler/gems/activeadmin-9739ac47dc4d/lib/active_admin/resource_controller/streaming.rb:12:in `index'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:815:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-3.8.1/lib/puma/configuration.rb:224:in `call'
[bundle].../gems/puma-3.8.1/lib/puma/server.rb:590:in `handle_request'
[bundle].../gems/puma-3.8.1/lib/puma/server.rb:425:in `process_client'
[bundle].../gems/puma-3.8.1/lib/puma/server.rb:289:in `block in run'
[bundle].../gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `call'
[bundle].../gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `76356e37185c8c4e515f14470feded659655405a`

**Comment by ajc113** [comment]
fixed location rb relationship issue
